### ISSUE TITLE
[v0.0.18] Impossible to install on official node-red-docker

### ISSUE THREAD

**Issue by MuadDibVV** [KevinBonnoron/node-red-contrib-freebox#116]
Hello,

  The last node-red-docker (v3.1.3) use npm 8.19.4 and node 16.20.2.
Unfortunately the last version of Release-IT (17.0.1) need node >= 18.
So it's impossible to install the last version of node-red-contrib-freebox on node-red-docker

**Comment by MuadDibVV** [comment]
It seems that the version will be upgraded soon :
https://github.com/node-red/node-red-docker/pull/402#issuecomment-1875934432

**Comment by KevinBonnoron** [comment]
Hello.

I think they are not gonna release the node 18 version until the release of node-red 4.0.0.
That's a shame because node 16 is not maintained since october 2023.

I've released a new version today (0.0.19) which should fix this issue

**Comment by MuadDibVV** [comment]
Perfect, thank you

**Comment by hardillb** [comment]
Node-RED container with NodeJS v18 are already available labelled as `latest-18` and have been since NR 3.0.x shipped.
