### ISSUE TITLE
Fatal error on api request

### ISSUE THREAD

**Issue by dathosim** [KevinBonnoron/node-red-contrib-freebox#34]
when api url is launched, node red crash...
(au simple connection is ok)

Trace : 

9 Oct 22:21:33 - [info] Node-RED version: v3.0.2
9 Oct 22:21:33 - [info] Node.js  version: v16.16.0
9 Oct 22:21:33 - [info] Linux 4.19.0-22-arm64 arm64 LE
9 Oct 22:21:34 - [info] Loading palette nodes
9 Oct 22:21:37 - [info] Dashboard version 3.2.0 started at /endpoint/ui
9 Oct 22:21:38 - [info] Settings file  : /etc/node-red/config.js
9 Oct 22:21:38 - [info] Context store  : 'default' [module=memory]
9 Oct 22:21:38 - [info] User directory : /config/node-red/
9 Oct 22:21:38 - [warn] Projects disabled : editorTheme.projects.enabled=false
9 Oct 22:21:38 - [info] Flows file     : /config/node-red/flows.json
9 Oct 22:21:38 - [info] Server now running at http://127.0.0.1:46836/
9 Oct 22:21:38 - [info] Starting flows
9 Oct 22:21:38 - [info] Connecting to freebox at https://mafreebox.freebox.fr:443
[22:21:38] INFO: Starting NGinx...
9 Oct 22:21:38 - [info] Started flows
9 Oct 22:21:38 - [info] Application registered
9 Oct 22:26:56 - [info] GET /connection
9 Oct 22:26:56 - [info] Session opened
9 Oct 22:26:57 - [info] GET /connection
9 Oct 22:28:50 - [info] Stopping flows
9 Oct 22:28:50 - [info] POST /login/logout
9 Oct 22:28:50 - [info] Stopped flows
9 Oct 22:28:50 - [info] Updated flows
9 Oct 22:28:50 - [info] Starting flows
9 Oct 22:28:50 - [info] Connecting to freebox at https://mafreebox.freebox.fr:443
9 Oct 22:28:50 - [info] Started flows
9 Oct 22:28:50 - [info] Session closed
9 Oct 22:28:50 - [info] Application registered
9 Oct 22:28:54 - [info] POST /home/nodes
9 Oct 22:28:54 - [info] Session opened
9 Oct 22:28:54 - [error] post https://mafreebox.freebox.fr:443/api/v9/home/nodes
9 Oct 22:28:54 - [red] Uncaught Exception:
9 Oct 22:28:54 - [error] Error: Unhandled error. (undefined)
    at new NodeError (node:internal/errors:372:5)
    at EventEmitter.emit (node:events:516:17)
    at /config/node-red/node_modules/node-red-contrib-freebox/src/nodes/freebox-server/freebox-server.js:257:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[22:28:54] WARNING: Node-RED crashed, halting add-on

**Comment by KevinBonnoron** [comment]
Hello !

What version of nodered are you using ? I din't made anychange since release 2.
What is the endpoint you are calling (/home/nodes) ? I don't find it in the documentation.

**Comment by dathosim** [comment]
Hello 

The NodeRed version was in my log : v3.0.2 😉
For the endpoint is in a doc but only on Freebox Os on your own Freebox (I don't understand why free don't publish this doc in his public doc)
But it's the same result with other end point like /tileset/all 

For your information, I use your contrib during one year to connect and get state on my Freebox security pack sensors in home assistant 
but last year (at the beginning of 22) your module crash NodeRed 
It's so sad 😞 

Nb : Are you French ?

**Comment by KevinBonnoron** [comment]
Oui je suis français :).

Je craignais que la montée de version de NodeRed provoque ce genre de soucis...
Je ne peux malheureusement pas regarder le problème maintenant, mais je vais regarder ce week-end et je ferais une version corrective.

En fait, ça fait quelques mois que j'ai des modifications sur ce repo que je dois publier ou je remanie un peu le code pour mieux gérer les erreurs (ça a toujours été un soucis et jamais simple à débuguer et j'ai envie d'avoir une solution un peu plus évolutive que ce qu'on a maintenant, avec typescript, une node globale permettant de tout gérer avec une liste déroulante des endpoint...).

Cela dit, c'est étrange qu'une palette puisse faire crasher NodeRed...

Merci pour le rapport de bug !

**Comment by dathosim** [comment]
Merci pour ton retour !
A dispo pour tester dès que tu as eu le temps de corriger
Pas d’urgence pour moi car par ailleurs je me sers de l’intégration Freebox de Ha pour remonter aussi l’état des capteurs de la Freebox 
Mais grâce à ton module j’arrivais a remonter le faite que le player était allumé par exemple et sur quel chaîne 😜
Merci d’avance

**Comment by KevinBonnoron** [comment]
Petite question. Dans la log d'erreur je vois que tu fais un POST vers /home/nodes. Dans la doc de la freebox je vois que ce endpoint n'est disponible qu'avec les verbes GET, PUT et PATCH.

La doc de ma freebox est en v8 et je vois que dans la log la tienne est en v9 ce qui pourrait expliquer le soucis.
Est-ce que tu aurais moyen de mettre le flow nodered ?

Merci

**Comment by KevinBonnoron** [comment]
Je viens de faire un fix (version 0.0.14). Dit moi si ça corrige ton problème de crash.
Dans tous les cas si tu utilises la node "api" et que dans l'input tu as un champ "msg.payload" alors la requête sera faite en POST. 2 possibilités pour corriger ça : 
- supprimer le payload
- ajouter un champ msg.method avec comme valeur GET dans l'input

**Comment by dathosim** [comment]
merci pour ton retour ! 
je test ça tout de suite et je te copie mon flow nodered 
C'est vrai que le dernier test que j'ai fait qui ne fonctionnait pas était pour /home/nodes
mais avant j'avais aussi eu des crashs sur d'autres API comme celle-ci /home/tileset/all
je test tout ça et reviens vers toi

**Comment by dathosim** [comment]
Re !
Tout refonctionne a merveille ! 
Un peu galéré pour mettre a jour le module dans nodered (qui est dans home assistant) mais j'y suis arrivé
Ensuite, ça a planté 1 ou 2 fois mais je suis reparti de 0 et j'ai redéclenché la demande d'autorisation sur la Freebox et hop voila...
MERCI !
NB : prochaine étape, j'aimerai pouvoir modifier la conf de la Freebox via home assistant > NodeRed - il semble que ça doit être possible via des requêtes PUT ;-)

**Comment by KevinBonnoron** [comment]
Parfait, je clôture ce ticket. Si tu as d'autres soucis n'hésites pas à me le remonter.
