### ISSUE TITLE
prettyDate / prettyData undeclared methods...

### ISSUE THREAD

**Issue by ybizeul** [KevinBonnoron/node-red-contrib-freebox#4]
It seems `api` calls `prettyDate` which is undeclared, in turn I was trying to declare it like it is declared in base module without success.

I'll figure it out eventually but if you could fix it that'd be great !

**Comment by KevinBonnoron** [comment]
Sure !

Thanks for the report

**Comment by KevinBonnoron** [comment]
Version 0.0.10 pushed with the fix, I close this issue.
Thanks again.
