### ISSUE TITLE
MODULE_NOT_FOUND, no freebox-server node, nor poll

### ISSUE THREAD

**Issue by happyjaxx** [KevinBonnoron/node-red-contrib-freebox#52]
Bonjour, Hello,

I've wanted to give this a try since a while but I've always stumbled upon installation issues... freebox-server (and poll) nodes are simply missing ... on two separate instances, whether the module is installed via GUI or CLI.
(both are Debian/aarch64 VMs hosted directly on the freebox itself, which is a funny usecase actually :-). If in any was it was a missing node dependency because of the plateform, I couldn't tell)

Initially, the nodes will show, and I get the freebox-server subselect in the connection node. but they disappear upon deployment, no more poll or freebox-server 🤷🏻‍♂️

node v18.15 / node-red 3.0.1

<img width="277" alt="Node-RED___nodered_flo_jaxx_org" src="https://github.com/KevinBonnoron/node-red-contrib-freebox/assets/935882/62ca20bb-f4c9-4eaf-a98c-ee71134cf97d">
<img width="567" alt="Node-RED___nodered_flo_jaxx_org" src="https://github.com/KevinBonnoron/node-red-contrib-freebox/assets/935882/b411b5f7-2775-4acc-9d54-64635bf68fd6">

This isn't life threatening, so no hurry, but any help will be appreciated :)

**Comment by KevinBonnoron** [comment]
Hello,

This is a strange behaviour. Do you anything about this palette in the logs? By any chance do you have another palette which have a node named "poll"? I know that node-red recommands to name node with the palette in front of this to avoid name clashing issue.

Regards

**Comment by happyjaxx** [comment]
Nothing out of the ordinary actually: here's a remove/install via GUI:
```
-----------------------------------------------------------
2023-05-25T12:26:41.714Z Remove : node-red-contrib-freebox

2023-05-25T12:26:41.803Z npm remove --no-audit --no-update-notifier --no-fund --save node-red-contrib-freebox
2023-05-25T12:26:49.463Z [out] 
2023-05-25T12:26:49.463Z [out] removed 336 packages in 6s
2023-05-25T12:26:49.490Z rc=0

-----------------------------------------------------------
2023-05-25T12:27:07.006Z Install : node-red-contrib-freebox 0.0.16

2023-05-25T12:27:07.056Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-freebox@0.0.16
2023-05-25T12:27:08.303Z [err] npm
2023-05-25T12:27:08.304Z [err]  WARN
2023-05-25T12:27:08.304Z [err]  config
2023-05-25T12:27:08.304Z [err]  production Use `--omit=dev` instead.
2023-05-25T12:27:35.520Z [out] 
2023-05-25T12:27:35.520Z [out] added 336 packages in 27s
2023-05-25T12:27:35.570Z rc=0
```
and nothing pops out using journalctl -f -u nodered

no other node named "poll"

**Comment by happyjaxx** [comment]
Oddly enough, 'poll' stays even after failure
<img width="303" alt="Node-RED___nodered_flo_jaxx_org" src="https://github.com/KevinBonnoron/node-red-contrib-freebox/assets/935882/a0cff5b3-da7c-4069-ba3d-53c2c9864057">

**Comment by KevinBonnoron** [comment]
So maybe a node named like any of the 4 others? The freebox-server seems to not be active

**Comment by happyjaxx** [comment]
No duplicates in the nodes neither (I remember having seen some with other palettes, but the error was different, some like "arleady declared/defined" more or less)... gonne try restart nodered with a dab more verbosity and see what's going on with some luck

**Comment by happyjaxx** [comment]
```
May 25 12:43:23 microdeb Node-RED[3075224]: Welcome to Node-RED
May 25 12:43:23 microdeb Node-RED[3075224]: ===================
May 25 12:43:23 microdeb Node-RED[3075224]: 25 May 12:43:23 - [info] Node-RED version: v3.0.2
May 25 12:43:23 microdeb Node-RED[3075224]: 25 May 12:43:23 - [info] Node.js  version: v18.15.0
May 25 12:43:23 microdeb Node-RED[3075224]: 25 May 12:43:23 - [info] Linux 5.10.0-21-arm64 arm64 LE
May 25 12:43:24 microdeb Node-RED[3075224]: 25 May 12:43:24 - [info] Loading palette nodes
May 25 12:43:30 microdeb Node-RED[3075224]: 25 May 12:43:30 - [info] Dashboard version 3.4.0 started at /ui
May 25 12:43:31 microdeb Node-RED[3075224]: 25 May 12:43:31 - [warn] ------------------------------------------------------
May 25 12:43:31 microdeb Node-RED[3075224]: 25 May 12:43:31 - [warn] [node-red-contrib-freebox/freebox-server] Error: Cannot find module '/home/nodered/package.json'
May 25 12:43:31 microdeb Node-RED[3075224]: Require stack:
May 25 12:43:31 microdeb Node-RED[3075224]: - /home/nodered/.node-red/node_modules/node-red-contrib-freebox/src/nodes/freebox-server/freebox-server.js
May 25 12:43:31 microdeb Node-RED[3075224]: - /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
May 25 12:43:31 microdeb Node-RED[3075224]: - /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
May 25 12:43:31 microdeb Node-RED[3075224]: - /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
May 25 12:43:31 microdeb Node-RED[3075224]: - /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
May 25 12:43:31 microdeb Node-RED[3075224]: - /usr/lib/node_modules/node-red/lib/red.js
May 25 12:43:31 microdeb Node-RED[3075224]: - /usr/lib/node_modules/node-red/red.js
May 25 12:43:31 microdeb Node-RED[3075224]: 25 May 12:43:31 - [warn] [node-red-contrib-freebox/poll] Error: Cannot find module 'node-red'
May 25 12:43:31 microdeb Node-RED[3075224]: Require stack:
May 25 12:43:31 microdeb Node-RED[3075224]: - /home/nodered/.node-red/node_modules/node-red-contrib-freebox/src/nodes/poll/poll.js
May 25 12:43:31 microdeb Node-RED[3075224]: - /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
May 25 12:43:31 microdeb Node-RED[3075224]: - /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
May 25 12:43:31 microdeb Node-RED[3075224]: - /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
May 25 12:43:31 microdeb Node-RED[3075224]: - /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
May 25 12:43:31 microdeb Node-RED[3075224]: - /usr/lib/node_modules/node-red/lib/red.js
May 25 12:43:31 microdeb Node-RED[3075224]: - /usr/lib/node_modules/node-red/red.js
May 25 12:43:31 microdeb Node-RED[3075224]: 25 May 12:43:31 - [warn] ------------------------------------------------------
```

Ahhhh.... getting somewhere, a double oddball ... why /home/nodered/package.json (and not under ~/.node-red/) and why not 'node-red' ?

**Comment by happyjaxx** [comment]
Got it working with minute changes, will PR
<img width="641" alt="Node-RED___nodered_flo_jaxx_org_and_nodered_microflo_____node-red_and_All_Inboxes" src="https://github.com/KevinBonnoron/node-red-contrib-freebox/assets/935882/809c9b81-0981-4029-a9f0-746eba44cac8">

**Comment by happyjaxx** [comment]
Mehh... lazy me didn't want to locally fork it... github's online tool is kinda weird, you got two PR's for the price of one 🤷🏻‍♂️

**Comment by KevinBonnoron** [comment]
Thanks, i validated both. I am making version 0.0.17, should be available soon. Tell me if that fix your problem
