### ISSUE TITLE
Error 403 since 0.0.17

### ISSUE THREAD

**Issue by MuadDibVV** [KevinBonnoron/node-red-contrib-freebox#55]
Hello,
  Since the 0.0.17 version I have this error and I can't use any more the solutions
"AxiosError: Request failed with status code 403"
Could you please correct it ?

(My other instance with 0.0.16 version wotk without problem)

Thank you

**Comment by KevinBonnoron** [comment]
Hello.

Tryed this morning with latest version and everything is working correctly.
Maybe try to delete the freebox config and create a new one? It will trigger a new connection on the freebox

**Comment by MuadDibVV** [comment]
Thanks @KevinBonnoron 

After recreating the freebox config (and re-authorize it on my Freebox), everything is ok again.
